// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/5/2025, 2:40:33 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/plugins/**/*.{js,ts,mjs}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/composables/**/*.{js,ts,mjs}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/utils/**/*.{js,ts,mjs}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/S3-File-Explorer/s3-file-explorer-app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;